// vuex module

export const UPDATE_TOP_POSITION = 'UPDATE_TOP_POSITION'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const UPDATE_TRANSITION_DIRECTION = 'UPDATE_TRANSITION_DIRECTION'
export const UPDATE_SHOW_HEADER = 'UPDATE_SHOW_HEADER'
export const UPDATE_SHOW_TABBAR = 'UPDATE_SHOW_TABBAR'
