// vux module
// 手机端app的设置
export const UPDATE_TOP_POSITION = 'UPDATE_TOP_POSITION'
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS'
export const UPDATE_TRANSITION_DIRECTION = 'UPDATE_TRANSITION_DIRECTION'
// 手机端layout设置
export const UPDATE_SHOW_HEADER = 'UPDATE_SHOW_HEADER'
export const UPDATE_SHOW_TABBAR = 'UPDATE_SHOW_TABBAR'
